### ISSUE TITLE
Wrong dimensions when trying to Model Inference

### ISSUE THREAD

**Issue by kenzokun** [Yinghao-Li/Sparse-CHMM#1]
Hello! I did the "Model Training" for CoNLL03 and when I was going to test the "Model Inference" I'm having the following issue:

RuntimeError: Error(s) in loading state_dict for SparseCHMM:
	size mismatch for neural_module.dir_param_base_module.emission_2e.weight: copying a param with shape torch.Size([64, 768]) from checkpoint, the shape in current model is torch.Size([128, 768]).
	size mismatch for neural_module.dir_param_base_module.emission_2e.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).

I made a copy of "**./scripts/infer-laptop.sh**" for CoNLL03, just changing the **output_dir** and **test_dir**.
Any ideas why this is happening or what should I do?

**Comment by Yinghao-Li** [comment]
Hi,

Sorry for the late response. I just saw this issue. I noticed that you have closed it. Have you solved the issue?

For CoNLL 2003, we have already prepared a script at `./scripts/train-conll.sh`. You can try that one and let me know if it does not work.

**Comment by kenzokun** [comment]
Hi! No problem!
Yes, a friend of mine helped me to find what it was.
It was the RELIAB_LVL="label" who was supposed to be changed to RELIAB_LVL="entity" for NER.

**Comment by Yinghao-Li** [comment]
Sounds good. Let me know if you have further questions or concerns!
